In [3]:
import pandas as pd
from google.colab import files

x = files.upload()

Saving Flavors.csv to Flavors.csv
Saving Ice Cream Ratings.csv to Ice Cream Ratings.csv
Saving LOTR 2.csv to LOTR 2.csv
Saving LOTR.csv to LOTR.csv

GROUP_BY AND AGG

In [4]:
df=pd.read_csv('Flavors.csv')
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [10]:
grp_by= df.groupby('Base Flavor')
grp_by

In [14]:
grp_by.mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [15]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [17]:
df.groupby('Base Flavor').sum(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [18]:
df.groupby('Base Flavor').max(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.8             7.6          16.6
Vanilla               10.0             8.0          18.0

In [19]:
df.groupby('Base Flavor').min(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.2             7.0          15.2
Vanilla                2.3             3.4           5.7

In [22]:
df.groupby('Base Flavor').agg({'Flavor Rating': ['mean','sum','max','min']})

            Flavor Rating
                     mean   sum   max  min
Base Flavor
Chocolate             8.4  25.2   8.8  8.2
Vanilla               5.7  34.2  10.0  2.3

In [23]:
df.groupby('Base Flavor').agg({'Flavor Rating': ['mean','sum','max','min'],'Texture Rating':['mean','sum','max','min']})

            Flavor Rating                  Texture Rating
                     mean   sum   max  min           mean   sum  max  min
Base Flavor
Chocolate             8.4  25.2   8.8  8.2       7.233333  21.7  7.6  7.0
Vanilla               5.7  34.2  10.0  2.3       5.650000  33.9  8.0  3.4

In [26]:
df.groupby(['Base Flavor','Liked']).mean(numeric_only=True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [27]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating': ['mean','sum','max','min']})

                  Flavor Rating
                           mean   sum   max  min
Base Flavor Liked
Chocolate   Yes             8.4  25.2   8.8  8.2
Vanilla     No              3.6  10.8   4.7  2.3
            Yes             7.8  23.4  10.0  6.5

In [28]:
df.groupby(['Base Flavor','Liked']).describe()

                  Flavor Rating                                             \
                          count mean       std  min   25%  50%   75%   max
Base Flavor Liked
Chocolate   Yes             3.0  8.4  0.346410  8.2  8.20  8.2  8.50   8.8
Vanilla     No              3.0  3.6  1.212436  2.3  3.05  3.8  4.25   4.7
            Yes             3.0  7.8  1.915724  6.5  6.70  6.9  8.45  10.0

                  Texture Rating            ...            Total Rating  \
                           count      mean  ...   75%  max        count
Base Flavor Liked                           ...
Chocolate   Yes              3.0  7.233333  ...  7.35  7.6          3.0
Vanilla     No               3.0  4.466667  ...  5.00  5.0          3.0
            Yes              3.0  6.833333  ...  7.25  8.0          3.0


                        mean       std   min    25%   50%    75%   max
Base Flavor Liked
Chocolate   Yes    15.700000  0.781025  15.2  15.25  15.3  15.95  16.6
Vanilla     No      8.066667  2.098412   5.7   7.25   8.8   9.25   9.7
            Yes    14.633333  2.950141  12.5  12.95  13.4  15.70  18.0

[3 rows x 24 columns]

MERGE,JOIN,CONCAT

In [31]:
df1= pd.read_csv('LOTR.csv')
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [33]:
df2=pd.read_csv('LOTR 2.csv')
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [34]:
df1.merge(df2)

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [35]:
df1.merge(df2,how="inner",on="FellowshipID")

   FellowshipID FirstName_x     Skills FirstName_y  Age
0          1001       Frodo     Hiding       Frodo   50
1          1002     Samwise  Gardening     Samwise   39

In [36]:
df1.merge(df2,how="inner",on=["FellowshipID",'FirstName'])

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [40]:
df1.merge(df2,how="outer")

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [39]:
df1.merge(df2,how="outer",on=["FellowshipID",'FirstName'])

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [41]:
df1.merge(df2,how="left")

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

In [42]:
df1.merge(df2,how='right')

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

In [43]:
df1.merge(df2,how="cross")

    FellowshipID_x FirstName_x     Skills  FellowshipID_y FirstName_y   Age
0             1001       Frodo     Hiding            1001       Frodo    50
1             1001       Frodo     Hiding            1002     Samwise    39
2             1001       Frodo     Hiding            1006     Legolas  2931
3             1001       Frodo     Hiding            1007      Elrond  6520
4             1001       Frodo     Hiding            1008    Barromir    51
5             1002     Samwise  Gardening            1001       Frodo    50
6             1002     Samwise  Gardening            1002     Samwise    39
7             1002     Samwise  Gardening            1006     Legolas  2931
8             1002     Samwise  Gardening            1007      Elrond  6520
9             1002     Samwise  Gardening            1008    Barromir    51
10            1003     Gandalf     Spells            1001       Frodo    50
11            1003     Gandalf     Spells            1002     Samwise    39
12            1003     Gandalf     Spells            1006     Legolas  2931
13            1003     Gandalf     Spells            1007      Elrond  6520
14            1003     Gandalf     Spells            1008    Barromir    51
15            1004      Pippin  Fireworks            1001       Frodo    50
16            1004      Pippin  Fireworks            1002     Samwise    39
17            1004      Pippin  Fireworks            1006     Legolas  2931
18            1004      Pippin  Fireworks            1007      Elrond  6520
19            1004      Pippin  Fireworks            1008    Barromir    51

In [48]:
df3=df1.join(df2, on='FellowshipID',how='outer',lsuffix='_Left',rsuffix='_Right')
df3

,FellowshipID,FellowshipID_Left,FirstName_Left,Skills,FellowshipID_Right,FirstName_Right,Age
NaN,0,NaN,NaN,NaN,1001.0,Frodo,50.0
NaN,1,NaN,NaN,NaN,1002.0,Samwise,39.0
NaN,2,NaN,NaN,NaN,1006.0,Legolas,2931.0
NaN,3,NaN,NaN,NaN,1007.0,Elrond,6520.0
NaN,4,NaN,NaN,NaN,1008.0,Barromir,51.0
0.0,1001,1001.0,Frodo,Hiding,NaN,NaN,NaN
1.0,1002,1002.0,Samwise,Gardening,NaN,NaN,NaN
2.0,1003,1003.0,Gandalf,Spells,NaN,NaN,NaN
3.0,1004,1004.0,Pippin,Fireworks,NaN,NaN,NaN

In [50]:
df4= df1.set_index('FellowshipID').join(df2.set_index('FellowshipID'),lsuffix='_Left',rsuffix='_Right')
df4

             FirstName_Left     Skills FirstName_Right   Age
FellowshipID
1001                  Frodo     Hiding           Frodo  50.0
1002                Samwise  Gardening         Samwise  39.0
1003                Gandalf     Spells             NaN   NaN
1004                 Pippin  Fireworks             NaN   NaN

In [52]:
  pd.concat([df1,df2])

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding     NaN
1          1002   Samwise  Gardening     NaN
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
0          1001     Frodo        NaN    50.0
1          1002   Samwise        NaN    39.0
2          1006   Legolas        NaN  2931.0
3          1007    Elrond        NaN  6520.0
4          1008  Barromir        NaN    51.0

In [54]:
  pd.concat([df1,df2],join='outer',axis=0)

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding     NaN
1          1002   Samwise  Gardening     NaN
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
0          1001     Frodo        NaN    50.0
1          1002   Samwise        NaN    39.0
2          1006   Legolas        NaN  2931.0
3          1007    Elrond        NaN  6520.0
4          1008  Barromir        NaN    51.0

In [56]:
  pd.concat([df1,df2],join='inner',axis=0)

   FellowshipID FirstName
0          1001     Frodo
1          1002   Samwise
2          1003   Gandalf
3          1004    Pippin
0          1001     Frodo
1          1002   Samwise
2          1006   Legolas
3          1007    Elrond
4          1008  Barromir